### ISSUE TITLE
CreationDateTimeField is not editable even with editable=True in version 1.5.7

### ISSUE THREAD

**Issue by grantmcconnaughey** [django-extensions/django-extensions#745]
I have a test that is passing using django-extensions 1.5.5 but fails in 1.5.7. The test tries to set a `CreationDateTimeField` and save a model, but the model does not get updated.

I have the following abstract model that some of my models inherit from:

```
class AuditModel(models.Model):
    date_created = fields.CreationDateTimeField(editable=True)
    # ...

    class Meta:
        abstract = True
```

And a model that extends `AuditModel`:

```
class SetPasswordToken(AuditModel):
    # Other fields
```

Here's the test:

```
def test_set_password_redirects_to_login_if_older_than_30_days(self):
    user = UserFactory()
    token = SetPasswordToken.objects.create(user=user,
                                            date_created=timezone.now() - relativedelta(days=60))

    # Test that relies on date_created not being today
```

When I use `pdb` after creating a `SetPasswordToken` I see that `token.date_created` is set to today, even though it is supposed to be set to 60 days ago. I also tried creating a token, explicitly setting `token.date_created`, then calling `token.save()` and it still will not be set to 60 days ago. This test works properly on version 1.5.5.

**Comment by trbs** [comment]
Hope this is solved by now, otherwise please open a new issue. Thanks !

**Comment by blueyed** [comment]
Not fixed / still a problem.
Likely due to https://github.com/django-extensions/django-extensions/pull/693 (https://github.com/django-extensions/django-extensions/commit/818f602214a3ea8144c184d5cf1ed41de0ae426c): Django overwrites editable/blank unconditionally (see https://github.com/django/django/pull/12274 for a fix).

**Comment by SteinRobert** [comment]
Maybe this helps someone - just a simple workaround:
```python
created = CreationDateTimeField(
        editable=True,
        auto_now_add=False,
        default=timezone.now()
)
```
This way I still have the current datetime as a default when the field is left empty. However, tt can be overridden.

**Comment by trbs** [comment]
Happy to accept a PR :-)

**Comment by blueyed** [comment]
Can we re-open it for now?

**Comment by trbs** [comment]
Better to keep this closed and directly submit a PR :-)
